version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: 
            echo "Hello World"

  node: circleci/node@1.1.6
  build-and-test:
    executor:
      name: node/default
    steps:
      working_directory: ~/cdond-autodeploy/frontend
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test

  node: circleci/node@1.1.6
  build-and-test:
    executor:
      name: node/default
    steps:
      working_directory: ~/cdond-autodeploy/backend
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test

workflows:
  default:
    jobs:
      - hello-world